### ISSUE TITLE
yolov5x 序列化报错

### ISSUE THREAD

**Issue by AlgoJay1991** [AIpakchoi/yolov5_tensorrt#2]
./yolov5x -s
Loading weights: ../yolov5x.wts
[07/24/2020-15:40:23] [E] [TRT] Parameter check failed at: ../builder/Network.cpp::addScale::434, condition: shift.count > 0 ? (shift.values != nullptr) : (shift.values == nullptr)
yolov5x: /home/admin/Projects/tensorrtx/yolov5x/common.hpp:189: nvinfer1::IScaleLayer* addBatchNorm2d(nvinfer1::INetworkDefinition*, std::map<std::__cxx11::basic_string<char>, nvinfer1::Weights>&, nvinfer1::ITensor&, std::__cxx11::string, float): Assertion `scale_1' failed.
Aborted (core dumped)

**Comment by AlgoJay1991** [comment]
did you meet the same issue before? and how can I to solve this problem, TX

**Comment by AIpakchoi** [comment]
@haige-algo 完全删除编译的文件，再试试，
For example:
                    cd build
                    rm -rf *
                    cmake ..
                    make
                    ./yolov5x -s
                    ./yolov5x -d ../images/

**Comment by AlgoJay1991** [comment]
@AIpakchoi 还是一样的问题, 是不是因为用的pt模型是今天刚下载最新的缘故, 但是https://github.com/wang-xinyu/tensorrtx 这个作者的yolov5s 我能正常跑通, 所以就很奇怪.

**Comment by AIpakchoi** [comment]
@haige-algo Ultralytics最新的pt已经升级到yolov5 v2.0了，又涨点了，我还没有试过。我等会试试，有结果与你反馈一下。我这边测试之前的pt都没有问题。

**Comment by AIpakchoi** [comment]
@haige-algo 我刚才试了一下，最新的yolov5 version2.0的pt确实无法运行，我稍后把旧版本的yolov5代码以及pt文件还有wts文件，都提供一下链接。

**Comment by AlgoJay1991** [comment]
@AIpakchoi 非常感谢你的工作

**Comment by hufangjian** [comment]
我也遇到相同的问题，谢谢！

**Comment by AIpakchoi** [comment]
@hufangjian 你好，请使用yolov5 v1.0版本的模型，这套TensorRT代码暂时只适用于yolov5 v1.0版本的模型。Ultralytics最新的yolov5已经升级到yolov5 v2.0了，改了模型结构，所以无法运行。我最新的repos里已经对此问题进行了说明，并且提供了7月5日之前v1.0版本的模型和训练代码，你可拿去使用。

**Comment by hufangjian** [comment]
多谢，请问一下7月5日的v1.0版代码在哪里下载？我要自己写训练数据。

**Comment by AIpakchoi** [comment]
@hufangjian 我这个repo里面的yolov5就是Ultralytics的v1.0版本的Pytorch训练测试代码包，我之前保留下来的。可拿去训练s,m,l,x四种模型。然后用我这repo里面的yolov5s,yolov5m,yolov4l,yolov5x去转TensorRT部署。

**Comment by hufangjian** [comment]
已经找到v1版本的多谢。

**Comment by cxww1991** [comment]
@haige-algo @AIpakchoi 遇到同样问题，在此留名感谢
